import React from 'react'
import vid from "../assets/IA_Model_Viedo.mp4"
import { FiPlay } from "react-icons/fi";
import { Link } from 'react-router-dom';
import BoxReveal from "@/Components/magicui/box-reveal";
import { ChevronRightIcon } from "lucide-react";
import SparklesText from "@/Components/magicui/sparkles-text";
import { NeonGradientCard } from "@/Components/magicui/neon-gradient-card";



const PreSection = () => {

    return (

        <section className=' max-md:flex-col max-md:px-4 max-md:w-full lg:mb-12 md:px-6  lg:mt-10 lx:mb-32 lg:px-10 xl:px-16 flex justify-center items-center m-auto mb-10 max-sm:mt-10 xxs:mt-0 xs:mt-9 md:mt-2  xl:mt-20  rounded-2xl shadow-sm '>
            <article className='w-1/2 max-xm:space-y-0  lg:px-8 py-4 max-md:w-full max-md:h-1/2 ' >
                <div className="h-full w-full max-w-[32rem] items-center justify-center overflow-hidden max-md:pt-0 ">
                    <SparklesText className="p-4 max-xs:text-2xl  max-sm:text-3xl md:text-4xl lg:px-0 xl:px-4 lg:text-5xl text-slate-800 dark:text-slate-300" text="HealthInsight AI" />
                    <BoxReveal boxColor={"transparent"} duration={1.2}>
                        <h2 className="mt-[.5rem] text-[1rem]">
                            <p className='p-4 xm:my-4 md:my-0 dark:text-white'>Designed for easy <span className="text-[#9822e0]">interaction</span> and <span className="text-[#9822e0]">accessibility</span>, They bridge the gap between patients and brain medical insights, Ultimately improving brain healthcare outcomes.</p>
                        </h2>
                    </BoxReveal>

                    <BoxReveal boxColor={"transparent"} duration={1.2}>
                        <div className="mt-[1.5rem] ">
                            <div className='grid grid-rows-2 p-8 xm:my-6 md:my-0 max-md:p-2 max-xm:gap-6 max-md:gap-8 gap-2 lg:py-0 xl:py-8'>
                                <p className=' flex text-xl max-sm:text-sm  gap-4 dark:text-white  font-semibold '><FiPlay className='w-fit text-3xl max-sm:text-sm text-[#9822e0]' /> Get an Easy Brain Diagnostic Generated By AI.</p>
                                <p className=' flex text-xl  max-sm:text-sm gap-4 dark:text-white font-semibold'><FiPlay className='w-fit text-3xl max-sm:text-sm text-[#9822e0]' />Get a specific Recommendations</p>
                            </div>
                        </div>
                    </BoxReveal>

                    <BoxReveal boxColor={"transparent"} duration={1.2}>
                        <Link to="/Home">
                            <div className="z-10 flex min-h-[6-rem]  max-xm:my-6 md:my-0 items-center  justify-center m-2">
                                    <button className='bg-[#000000] dark:bg-[#461763] md:ml-10 font-semibold px-12 py-2.5 rounded-lg '> <span className="group text-white inline-flex items-center">
                                            Get Started
                                            <ChevronRightIcon className="ml-1  h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
                                        </span></button>
                            </div>
                        </Link>
                    </BoxReveal>
                </div>
            </article>

            <article className='w-1/2 max-sm:w-full max-md:w-full sm:p-4 xs:p-4 xm:p-8 max-md:h-1/2 md:pr-0 lg:px-4 lg:p-8 flex max-sm:p-4 justify-center items-center'>
                <NeonGradientCard className=" w-full  max-sm:h-48 max-sm:w-full sm:h-80 md:h-64 lg:h-80 max-w-xl    ">
                    <p className='w-full h-full rounded-lg bg-[#c5afd6b9]  dark:bg-[#291738b9] py-2'>
                        <video className=' rounded-lg h-full w-full  flex' src={vid} controls autoPlay muted loop ></video>
                    </p>
                </NeonGradientCard>

                
            </article>
        </section>
    )
}

export default PreSection
